steps:
  - command: ./.buildkite/scripts/ecr-login.sh
    label: ":hammer:docker-build:hammer:"
    agents:
      - "role=agent"

  - command: ./.buildkite/scripts/build.sh
    label: ":hammer:docker-build:hammer:"
    agents:
      - "role=agent"

  - wait

  - command: ./.buildkite/scripts/tag.sh
    label: "tag"
    agents:
      - "role=agent"

  - wait

  - command: ./.buildkite/scripts/push.sh
    label: "push"
    agents:
      - "role=agent"
