steps:
  - command: ./.buildkite/scripts/build.sh
    label: ":hammer:docker-build:hammer:"
    agents:
      - "role=agent"
  - wait

  - command: ./.buildkite/scripts/tag.sh
    label: "tag"
    agents:
      - "role=agent"

  - wait

  - command: ./.buildkite/scripts/push.sh
    label: "push"
    plugins:
      docker#v1.1.0:
        image: "docker:latest"
        mounts:
          - /var/run/docker.sock:/var/run/docker.sock
    agents:
      - "role=agent"
